sudo: false

scripts:
  - npm install
  - npm run build:win --config buildConfigs/config.mac.json

# build:
#   - npm build:win --config config.mac.json

language: node_js
node_js:
  - '16.20.0'

os:
  - osx
