sudo: false

scripts:
  - npm install
  - npm run build:mac --config buildConfigs/config.mac.json

# build:
#   - npm build:win --config config.mac.json

language: node_js
node_js:
  - '16.20.0'

os:
  - osx

    before_deploy:
      # Set up git user name and tag this commit
      - git config --local user.name "GIORGIPUNK123"
      - git config --local user.email "giorgirock@hotmail.com"
      - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
      - git tag $TRAVIS_TAG
    deploy:
      provider: releases
      api_key: "kvitCEdEhA1sbCRJIDox/z5vlu4JcbHYpn71kI4S9FDeX/2pLD3EUpdVtLo+gC03n7+NCcnjQxFOifeD8zRyZUlea7Zt3WFYrqeh+FlcCXWLZSPtt/9RYdrOtVKS5Q/46AfnQJxPtSBq+NCOX4QAwU3KHLCLGGMDVI2ubVTHHFCn8Unb7ha1/djeI2XLOZ4naoONmLLGodoQXUt8VHALzzlkoxFVubA/iRCyOOvukCBenl4xo7xN6NtscMBDyNdHMT3GDCibUK99Yij5K+9dnpor4cLOi4m1h9q2R3AmzfrqDdUWbY/Oi7QE3PhOYV3VO6rY7QINYCrE8cBZDhHPhXnc/m++Y2yTbe0UuRMiyT701ugCa0vkt3yITYppYigxdG8gRo9W4RJWQHDV+8xFMXW35fivWR8HnG/yvbt6nqgYJl+7MtR4a36kYOTuRVEJQB32iF/2eGkCjAzYrnn/Gg8hOBT8Bqs4/5/nlqKCYD4Nvq5sXDzY89iinOmr0/Fp+zdjwNDenuUX+UHBtFTreiS52EV1vAyKjUxFKEedSM+T8UZl69CZmuq2sUV39Gkh1SaMAVz804+F4efAT1DaGes3F98mISCOispB7J1UyNdCQ3g8YJG5JFOhje/kfdro7jH9h/6mSxb6mTtCq+He75w+OE0NeG2tR2CQoQJwLsQ="
      file: "FILE TO UPLOAD"
      skip_cleanup: true