language: node_js
node_js:
  - '16.20.0'

os:
  - osx

before_install:
  - npm install -g npm@latest

install:
  - npm install

script:
  - npm run build:mac --config buildConfigs/config.mac.json

before_deploy:
  - git config --local user.name "GIORGIPUNK123"
  - git config --local user.email "giorgirock@hotmail.com"
  - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
  - git tag $TRAVIS_TAG

deploy:
  provider: releases
  api_key: $SECRET_GIT_TOKEN
  file: dist/mac/Write-1.0.0-mac.zip
  skip_cleanup: true
  on:
    repo: GIORGIPUNK123/Write
    branch: development
