sudo: false

scripts:
  - npm install
  - npm run build:mac --config buildConfigs/config.mac.json

# build:
#   - npm build:win --config config.mac.json

language: node_js
node_js:
  - '16.20.0'

os:
  - osx

before_deploy:
  # Set up git user name and tag this commit
  - git config --local user.name "GIORGIPUNK123"
  - git config --local user.email "giorgirock@hotmail.com"
  - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
  - git tag $TRAVIS_TAG
deploy:
  provider: releases
  api_key: $SECRET_GIT_TOKEN
  file: 'FILE TO UPLOAD'
  skip_cleanup: true
